// <auto-generated />
using System;
using HebertApp.API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HebertApp.API.Migrations
{
    [DbContext(typeof(HebertAppAPIContext))]
    [Migration("20190417102718_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034");

            modelBuilder.Entity("HebertApp.API.Models.Job", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("chemin")
                        .IsRequired()
                        .HasColumnName("chemin")
                        .HasColumnType("TEXT");

                    b.Property<string>("cheminShp")
                        .IsRequired()
                        .HasColumnName("cheminShp")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("dateDebut")
                        .HasColumnName("dateDebut")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("dateFin")
                        .HasColumnName("dateFin")
                        .HasColumnType("TEXT");

                    b.Property<string>("parametres")
                        .HasColumnName("parametres")
                        .HasColumnType("TEXT");

                    b.Property<string>("shp")
                        .IsRequired()
                        .HasColumnName("shp")
                        .HasColumnType("TEXT");

                    b.Property<string>("statut")
                        .IsRequired()
                        .HasColumnName("statut")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Job");
                });
#pragma warning restore 612, 618
        }
    }
}
